### ISSUE TITLE
Update actions/core for set-output/state deprecation

### ISSUE THREAD

**Issue by pbrisbin** [haskell/actions#123]
Seeing these warnings when using `setup-hlint`, the other actions may be affected too:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

As visible the linked documentation, `set-output` (and `save-state`) are considered dangerous and have been replaced with environment files. If I understand correctly, you just need to update to `actions/core@1.10.0`.

It looks like you use Dependabot to keep your actions up to date; for what it's worth, you could extend that to manage these dependencies too.

**Comment by andreasabel** [comment]
This issue was fixed by https://github.com/haskell/actions/commit/97d6391f4afce6357da121cd189e6a1cce8d13ec#r93910507 , released with v2.0.2.

**Comment by pavelzw** [comment]
@andreasabel pbrisbin meant updating `@actions/core` in `hlint-setup`, not in `setup`. [Here](https://github.com/haskell/actions/blob/93635e8c4ac823f55cf3444537a63d3f2fd589de/hlint-setup/package.json#L30) we can still see that it is not up to date.

Ref #149

**Comment by andreasabel** [comment]
Ah, sorry, my bad, I confused this.
